name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base
  - r-tidyverse=2.0.0
  - r-ggdendro=0.2.0
  - r-dynamictreecut=1.63_1
  - r-fastcluster=1.2.6
  - r-wgcna=1.71
  - r-threejs=0.3.3
  - r-kableextra=1.4.0
  - r-statip=0.2.3
  - r-bookdown=0.40
  - r-downlit=0.4.4
  - r-patchwork=1.2.0
  - r-ggbeeswarm=0.7.2
  - r-here=1.0.1
  - r-biocmanager=1.30.24
  - r-ggally=2.2.1
  - r-ggridges=0.5.6
  - r-gplots=3.1.3.1
  - r-argparser=0.7.2
  - r-shiny=1.9.1
  - bioconductor-affy=1.80.0
  - bioconductor-affydata=1.50.0
  - bioconductor-impute=1.76.0
  - bioconductor-hgu95av2cdf=2.18.0
  - bioconductor-fgsea=1.28.0
  - bioconductor-go.db=3.18.0
  - bioconductor-biomart=2.58.0
  - bioconductor-summarizedexperiment=1.32.0
  - bioconductor-limma=3.58.1
  - bioconductor-deseq2=1.42.0
  - bioconductor-gseabase=1.64.0
